### ISSUE TITLE
SKlearn PAV extrapolation and intrapolation weird

### ISSUE THREAD

**Issue by vergep** [NetherlandsForensicInstitute/lir-deprecated#32]
The predictions of PAV calibrated are weird. If you look at the PAV plot, the prediction line has a weird shape when inter- or extrapolating. Suggestion: give extrapolated LLRs values -/+ Inf (so plot vertical lines at the x-limits of the PAV line), and use linear interpolation on the LLR scale.

**Comment by TimoMatzen** [comment]
Hmm I wil check whether linear interpolation on the LLR scale helps, good suggestion. I don't know whether I agree on giving extrapolated LLRS values -/+ inf. What is the reason that you want to do that? Because in reality if you would have such an LR it wouldn't take on a value of inf right?
