### ISSUE TITLE
PAV plot for completely separated data weird

### ISSUE THREAD

**Issue by vergep** [NetherlandsForensicInstitute/lir-deprecated#40]
The PAV-plot for completely seperated data is wierd. It gives points around de identity line. I've an example and of a PAV-plot generated by LIR and a PAV-plot generated by an R-script of mine. Data is also included.
[PAV-plot A vs C by R.pdf](https://github.com/NetherlandsForensicInstitute/lir/files/6847744/PAV-plot.A.vs.C.by.R.pdf)
[lrs_A,C.xlsx](https://github.com/NetherlandsForensicInstitute/lir/files/6847752/lrs_A.C.xlsx)
![PAV-plot_A_vs_C_by_LIR](https://user-images.githubusercontent.com/65766436/126314657-8edfabfa-2638-4657-977d-6a4a023b793a.png)

**Comment by wowtor** [comment]
Simple test case to reproduce this issue:

```py
lrs = np.array([1.e-20, 2.e-20, 1.e-11])
labels = np.array([0, 0, 1])
pav_lrs = lir.calibration.IsotonicCalibrator().fit_transform(lrs, labels)
np.testing.assert_equal(pav_lrs, np.array([0, 0, np.inf]))
```

**Comment by TimoMatzen** [comment]
@wowtor so what you expect is that the array would be np.array([-np.inf, -np.inf, np.inf]) right?

**Comment by wowtor** [comment]
> @wowtor so what you expect is that the array would be np.array([-np.inf, -np.inf, np.inf]) right?

No, the assert statement should succeed, meaning that `pav_lrs` should be 0, 0, inf

**Comment by TimoMatzen** [comment]
But with me it succeeds :s

**Comment by TimoMatzen** [comment]
@vergep en @wowtor ik kan het probleem niet reproduceren. Als ik Wauter zijn voorbeeld run dan krijg ik precies wat je verwacht en als ik peter zijn data gebruik krijg ik het volgende plotje:

![bug_example_pav](https://user-images.githubusercontent.com/37905386/132660679-52955d77-6c8b-45dc-b091-a084dc4975a0.png)

Volgens mij is dat precies wat je verwacht toch?

**Comment by vergep** [comment]
Hoi Timo,

Ik kan je plotje helaas niet zien.

Groet,

Peter

**Comment by wowtor** [comment]
```py
import numpy as np
import lir
lrs = np.array([1.e-20, 2.e-20, 1.e-11])
labels = np.array([0, 0, 1])
pav_lrs = lir.calibration.IsotonicCalibrator().fit_transform(lrs, labels)
np.testing.assert_equal(pav_lrs, np.array([0, 0, np.inf]))
```
```
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/home/wauter/workspace/lir/venv/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 345, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/home/wauter/workspace/lir/venv/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 934, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/home/wauter/workspace/lir/venv/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 1 / 3 (33.3%)
Max absolute difference: 1.e-09
Max relative difference: inf
 x: array([0.e+00, 1.e-09,    inf])
 y: array([ 0.,  0., inf])
```

```sh
$ git rev-parse HEAD
341b9db3153da0b00c7bfdae01b897f2850b4050
$ python3 --version
Python 3.8.10
$ pip freeze
appdirs==1.4.4
astunparse==1.6.3
black==21.7b0
click==8.0.1
cycler==0.10.0
joblib==1.0.1
kiwisolver==1.3.1
matplotlib==3.4.3
mypy-extensions==0.4.3
numpy==1.21.2
pathspec==0.9.0
Pillow==8.2.0
pyparsing==2.4.7
python-dateutil==2.8.1
regex==2021.7.6
scikit-learn==0.24.2
scipy==1.7.1
six==1.16.0
threadpoolctl==2.1.0
tomli==1.1.0
tqdm==4.62.2
```

**Comment by TimoMatzen** [comment]
@wowtor @vergep the reason that I was not having the issue was because I was running an older version of scikit-learn. With scikit-learn 0.22.1 this problem does not exist, therefore a temporary work around is to locally change your scikit-learn version to `scikit-learn<0.24.0`. In the meantime I will try and find what was changed in sklearn resulting in this problem.
