### ISSUE TITLE
unittest vs. pytest 

### ISSUE THREAD

**Issue by HHoofs** [NetherlandsForensicInstitute/lir-deprecated#9]
In the `pythonapp.yml` pytest is stated
```
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
```
while `unittest` is used

**Comment by HHoofs** [comment]
I fixed this in https://github.com/HolmesNL/lir/pull/8 but don't know if this fix is intended

**Comment by HHoofs** [comment]
> I fixed this in #8 but don't know if this fix is intended

Wel the fix was intended, but I don't know if that is the intended way to go 😄

**Comment by HHoofs** [comment]
I've closed my PR, but i think this issue remains. What should it be?

**Comment by wowtor** [comment]
Currently pytest is used to collect tests; the tests themselves are `unittest`. Does it need to be changed or close the issue?

**Comment by wowtor** [comment]
Not sure what to do with this; close for now
